name: Update JSON

on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate JSON
        working-directory: src
        run: |
          python main.py --mode song > ../data/songs.json
          python main.py --mode character > ../data/characters.json

      - name: Create p-r
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update JSON
          delete-branch: true
          title: Update JSON
